import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";

const recursive = Recursive({
  subsets: ['latin'],
  display: 'swap', // 'swap' minimizes layout shift
  // Optionally, you can add a CSS variable name for use in CSS/Tailwind
  variable: '--font-recursive', 
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // FIX: Use a template literal (backticks ``) to combine the variable and the string
    <html lang="en" className={`${recursive.className} flex justify-center min-h-screen`}>
      <body className="w-1/2 p-5">{children}</body>
    </html>
  );
}
